name: Ollama API

on:
  # Run the workflow on push to main branch
  push:
    branches: ["main"]

  # Allow to trigger the workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted", "main"]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies using bun because it's faster
        run: bun i

      - name: Create .env file
        run: echo "${{secrets.ENV_FILE }}" > .env
